### ISSUE TITLE
请问你们在真机上有部署过的么 swarm_ros_bridge 有相关的配置的文件么

### ISSUE THREAD

**Issue by Renaissnance** [Jiang-Yufei/Multi-agent-exploration#1]

**Comment by Jiang-Yufei** [comment]
[ros_sub_pub.hpp.txt](https://github.com/user-attachments/files/16679684/ros_sub_pub.hpp.txt)
[ros_topics.yaml.txt](https://github.com/user-attachments/files/16679687/ros_topics.yaml.txt)
[CMakeLists.txt](https://github.com/user-attachments/files/16679690/CMakeLists.txt)
你可以参考一下（加.txt是因为附件不支持对应格式）

**Comment by Renaissnance** [comment]
好的 感谢您 帮了很大忙
